AllCops:
  Exclude:
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'

Documentation:
  Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 0

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 800
